mysql:
  image: mysql/mysql-server
  ports:
    - "3306:3306"
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=root
api:
  build: ./api
  links:
    - mysql:mysql
  ports:
    - "8080:8080"
  environment:
    - PORT=8080
    - MYSQL_HOST=mysql
    - MYSQL_USER=root
    - MYSQL_PASSWORK=root
